### PR TITLE
say something

### PR DESCRIPTION
**Pull request by Gudolf**
it s me

### CODE REVIEW

**Comment by lakviat** [comment]
Hei @Gudolf could you please make sure your file is executable

**Comment by Gudolf** [comment]
no @lakviat

**Review by lakviat — CHANGES_REQUESTED** [review]
Please fix the java virtual environment and push it again @Gudolf

**Comment by Delly777** [comment]
I can also text here is it okay?

**Comment by lakviat** [comment]
LGTM! -> Looks good to me ..

**Pull request merged**
